### PR TITLE
 fix(index): path to data

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Don't forget to as add "marcosc" on NPM so I can publish 🙏

**Comment by marcoscaceres** [comment]
I replicated these changes on the server, works well :)

**Comment by sidvishnoi** [comment]
I've added a "publish to npm on release" workflow using GitHub actions. So, everytime we make a release, it gets published automatically. Haven't tested yet though.

**Review by sidvishnoi — APPROVED** [review]

**Comment by sidvishnoi** [comment]
and it works! 🎉

**Comment by marcoscaceres** [comment]
Awesome! You will have to teach me how to use those one day.

**Pull request merged**
